SELECT
    REST_INFO.FOOD_TYPE,
    REST_INFO.REST_ID,
    REST_INFO.REST_NAME,
    MAX_FAV.FAVORITES
FROM
    REST_INFO
JOIN
(   SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS FAVORITES
    FROM
        REST_INFO
    GROUP BY
        FOOD_TYPE
 ) AS MAX_FAV
ON
    MAX_FAV.FAVORITES = REST_INFO.FAVORITES

GROUP BY
    FOOD_TYPE

ORDER BY
    FOOD_TYPE DESC