-- 코드를 입력하세요
SELECT
REST_INFO.REST_ID,
REST_INFO.REST_NAME,
REST_INFO.FOOD_TYPE,
REST_INFO.FAVORITES,
REST_INFO.ADDRESS,
AVG_QUERY.SCORE
FROM
    REST_INFO
JOIN
    ( SELECT
    REVIEW_ID,
    REST_ID,
    MEMBER_ID,
    ROUND(AVG(REVIEW_SCORE),2) AS SCORE,
    REVIEW_TEXT
 
    FROM
        REST_REVIEW

    GROUP BY
        REST_ID) AS AVG_QUERY
ON
    REST_INFO.REST_ID = AVG_QUERY.REST_ID

WHERE
    REST_INFO.ADDRESS LIKE '서울%'

ORDER BY
    SCORE DESC, FAVORITES DESC