-- 코드를 입력하세요
SELECT
    USED_GOODS_USER.USER_ID,
    USED_GOODS_USER.NICKNAME,
    TOTAL_P_TABLE.TOTAL_PRICE
FROM
    USED_GOODS_USER
JOIN
( SELECT
    U.USER_ID,
    SUM(I.PRICE) AS TOTAL_PRICE
FROM
    USED_GOODS_BOARD I
JOIN
    USED_GOODS_USER U
ON
    I.WRITER_ID = U.USER_ID

WHERE
    I.STATUS LIKE 'DONE'

GROUP BY 
    U.USER_ID) AS TOTAL_P_TABLE

ON
    USED_GOODS_USER.USER_ID = TOTAL_P_TABLE.USER_ID

WHERE
    TOTAL_PRICE >= 700000

ORDER BY
    TOTAL_P_TABLE.TOTAL_PRICE
