-- 코드를 입력하세요
# SELECT
# FIRST_HALF.FLAVOR
# FROM
#     FIRST_HALF

# LEFT JOIN
#     ICECREAM_INFO
# ON
#     FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
# WHERE
#     (TOTAL_ORDER >= 3000)
#     AND
#     (INGREDIENT_TYPE LIKE '%ruit_based')
# ORDER BY
#     TOTAL_ORDER

SELECT
    F.FLAVOR
FROM
    FIRST_HALF F
JOIN
    ICECREAM_INFO I
ON
  F.FLAVOR = I.FLAVOR
  
WHERE
    F.TOTAL_ORDER > 3000
    AND I.INGREDIENT_TYPE LIKE 'fruit%'

ORDER BY
    F.TOTAL_ORDER DESC