-- 코드를 작성해주세요
SELECT
    HR_EMPLOYEES.DEPT_ID,
    HR_DEPARTMENT.DEPT_NAME_EN,
    ROUND(AVG(HR_EMPLOYEES.SAL),0) AS AVG_SAL
FROM
    HR_EMPLOYEES
JOIN
    HR_DEPARTMENT
ON
    HR_EMPLOYEES.DEPT_ID = HR_DEPARTMENT.DEPT_ID

GROUP BY
    DEPT_ID

ORDER BY
    AVG_SAL DESC