-- 10 이하의 물고기 10cm로 취급하여 평균길이 구하기.
SELECT
    COUNT(FISH_INFO.ID) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    AVG_TABLE.FISH_TYPE
FROM
    FISH_INFO
JOIN
( SELECT
    FISH_TYPE,
    AVG(COALESCE(LENGTH,10)) AS AVG_LENGTH
  FROM
    FISH_INFO
  GROUP BY
    FISH_TYPE) AS AVG_TABLE

ON
    FISH_INFO.FISH_TYPE = AVG_TABLE.FISH_TYPE

WHERE
    AVG_TABLE.AVG_LENGTH >= 33


GROUP BY
    FISH_TYPE

ORDER BY
    FISH_TYPE

