-- 코드를 입력하세요
SELECT
    PRICE AS PRICE_GROUP,
    COUNT(PRODUCT_ID) AS PRODUCTS
FROM
    (SELECT
    PRODUCT_ID,
    FLOOR(PRICE/10000)*10000 AS PRICE
    FROM
        PRODUCT) AS origin

GROUP BY PRICE
ORDER BY PRICE